substitutions:
  name: cabinet-ac
  climate_name: Cabinet Climate
  follow_me_sensor: sensor.bedroom_temperature

esphome:
  project:
    name: "dudanov.electrolux-ac-control"
    version: "1.0"

dashboard_import:
  package_import_url: github://dudanov/iot-uni-dongle/electrolux-ac-esp8266.yaml

packages:
  remote_package:
    url: https://github.com/dudanov/iot-uni-dongle
    refresh: 0d
    files: [
      # Main dongle package
      esphome/iot-uni-dongle.yaml,
      # TSOP
      esphome/remote/tsop.yaml,
      # IR LED
      #esphome/remote/led.yaml,
      # Electrolux EACS. Select your model HERE.
      esphome/climate/midea/electrolux.yaml,
      # "Beeper feedback" switch
      esphome/climate/midea/common/beeper.yaml,
      # "Display toggle" button. Works only via IR transmitter for Electrolux EACS.
      esphome/climate/midea/common/display.yaml,
      # "FollowMe" capability via HomeAssistant service.
      esphome/climate/midea/common/follow_me/service.yaml,
      # "FollowMe" capability via HomeAssistant sensor.
      # Sensor entity name setting up via ${follow_me_sensor} substitution.
      esphome/climate/midea/common/follow_me/sensor.yaml,
    ]

# Uncomment for use button as AC power control
#binary_sensor:
#  - platform: gpio
#    id: flash_button
#    pin:
#      number: GPIO0
#      inverted: true
#    filters:
#      - delayed_on_off: 50ms
#    on_click:
#        lambda: |-
#            if (id(midea_climate).mode == CLIMATE_MODE_OFF)
#              id(midea_climate).do_power_on();
#            else
#              id(midea_climate).do_power_off();
