substitutions:
  name: cabinet-ac
  climate_name: Cabinet Climate
  follow_me_sensor: sensor.bedroom_temperature

esphome:
  project:
    name: "dudanov.electrolux-ac-control"
    version: "1.0"

dashboard_import:
  package_import_url: github://dudanov/iot-uni-dongle/electrolux-ac-esp8266.yaml

packages:
  remote_package:
    url: https://github.com/dudanov/iot-uni-dongle
    refresh: 0d
    files: [
      # Main dongle package
      esphome/hardware/iot-uni-dongle.yaml,
      # TSOP
      esphome/hardware/remote/tsop.yaml,
      # IR LED
      #esphome/hardware/remote/led.yaml,
      # Electrolux EACS. Select your model HERE.
      esphome/climate/midea/electrolux.yaml,
      # "Power toggle" on hardware button click. (Not working yet. Support will be in next ESPHome release 2022.6)
      #esphome/climate/midea/common/button.yaml,
      # "Beeper feedback" switch
      esphome/climate/midea/common/beeper.yaml,
      # "Display toggle" button. Works only via IR transmitter for Electrolux EACS.
      esphome/climate/midea/common/display.yaml,
      # "Swing step" button. Works only via IR transmitter.
      esphome/climate/midea/common/swing.yaml,
      # "FollowMe" capability via HomeAssistant service.
      esphome/climate/midea/common/follow_me/service.yaml,
      # "FollowMe" capability via HomeAssistant sensor.
      # Sensor entity name setting up via ${follow_me_sensor} substitution.
      esphome/climate/midea/common/follow_me/sensor.yaml,
    ]
