esphome:
  project:
    name: "dudanov.electrolux-ac"
    version: "1.0.0"

substitutions:
  node_name: cabinet-ac
  climate_name: Cabinet Climate
  follow_me_sensor: sensor.bedroom_temperature

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

packages:
  remote_package:
    url: https://github.com/dudanov/iot-uni-dongle
    refresh: 0d
    files: [
      # Main dongle package
      esphome/iot-uni-dongle.yml,
      # Electrolux EACS. Select your model HERE.
      esphome/climate/midea/electrolux.yml,
      # "Beeper feedback" switch
      esphome/climate/midea/common/beeper.yml,
      # "Display toggle" button. Works only via IR transmitter for Electrolux EACS.
      esphome/climate/midea/common/display.yml,
      # "FollowMe" capability via HomeAssistant service.
      esphome/climate/midea/common/follow_me/service.yml,
      # "FollowMe" capability via HomeAssistant sensor.
      # Sensor entity name setting up via ${follow_me_sensor} substitution.
      esphome/climate/midea/common/follow_me/sensor.yml,
    ]

# Uncomment for use button as AC power control
#binary_sensor:
#  - platform: gpio
#    id: flash_button
#    pin:
#      number: GPIO0
#      inverted: true
#    filters:
#      - delayed_on_off: 50ms
#    on_click:
#        lambda: |-
#            if (id(midea_climate).mode == CLIMATE_MODE_OFF)
#              id(midea_climate).do_power_on();
#            else
#              id(midea_climate).do_power_off();
