esphome:
  name: example
  platform: esp8266
  board: esp12e
  platformio_options:
    upload_speed: 2000000

wifi:
  ssid: "SSID"
  password: "PASSWORD"
  ap:
    ssid: "iot-uni-dongle"
    password: "12345678"

captive_portal:

api:

ota:

logger:
  baud_rate: 0

uart:
  tx_pin: 1
  rx_pin: 3
  baud_rate: 9600

# Uncomment for use button as AC power control
#binary_sensor:
#  - platform: gpio
#    id: flash_button
#    pin:
#      number: GPIO0
#      inverted: true
#    filters:
#      - delayed_on_off: 50ms
#    on_click:
#        lambda: |-
#            if (id(my_climate).mode == CLIMATE_MODE_OFF)
#              id(my_climate).do_power_on();
#            else
#              id(my_climate).do_power_off();

climate:
  - platform: midea
    id: my_climate
    name: AC01
    period: 1s
    num_attempts: 3
    timeout: 2s
    beeper: false
    autoconf: true
    visual:
      min_temperature: 17 °C
      max_temperature: 30 °C
      temperature_step: 0.5 °C
    supported_modes:
      - FAN_ONLY
      - HEAT_COOL
      - COOL
      - HEAT
      - DRY
    custom_fan_modes:
      - SILENT
      - TURBO
    supported_presets:
      - ECO
      - BOOST
      - SLEEP
    custom_presets:
      - FREEZE_PROTECTION
    supported_swing_modes:
      - VERTICAL
      - HORIZONTAL
      - BOTH
    outdoor_temperature:
      name: Temp
    power_usage:
      name: Power
    humidity_setpoint:
      name: Hum
